/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario2;

import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sys515
 */
public class EditarResolucion extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection tr = con.conexion();
    private int año = 0;
    private int mes = 0;
    private int dia = 0;
    private String id;

    /**
     * Creates new form Resolucion
     */
    public EditarResolucion(String x[]) {
        initComponents();
        this.setTitle("Editar Resolución - Sistema Inventario BTZ");
        Serie.setText(x[0]);
        Final.setText(x[2]);
        Inicio.setText(x[1]);
        NR.setText(x[5]);
        id = x[7];
        contra.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
             contra.setText(null);
             
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Inicio = new javax.swing.JTextField();
        Final = new javax.swing.JTextField();
        Serie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 111, 172));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InicioKeyTyped(evt);
            }
        });
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 40, -1));

        Final.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FinalKeyTyped(evt);
            }
        });
        jPanel1.add(Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 50, -1));
        jPanel1.add(Serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Autorizar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));
        jPanel1.add(NR, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 60, 120, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha Autorizacion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Resolución");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 480, -1));

        Fecha.setDateFormatString("yyyy-MM-d");
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Serie");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-guardar-50.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-guardar-filled-50.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rango");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Incial");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Final");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Número  De Resolución");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 110, -1));

        contra.setText("jPasswordField1");
        contra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraFocusGained(evt);
            }
        });
        jPanel1.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InicioKeyTyped
        int k = (int) evt.getKeyChar();
        if (k >= 97 && k <= 127 || k >= 58 && k <= 97) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 241 || k == 209) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k >= 33 && k <= 47) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar Simbolos!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 10) {
            Inicio.transferFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_InicioKeyTyped

    private void FinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalKeyTyped
        int k = (int) evt.getKeyChar();
        if (k >= 97 && k <= 127 || k >= 58 && k <= 97) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 241 || k == 209) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k >= 33 && k <= 47) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar Simbolos!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 10) {
            Final.transferFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_FinalKeyTyped
    private Boolean vef() {
        Boolean r = false;
        try {
            Statement sx = tr.createStatement();
            ResultSet Ca = sx.executeQuery("select id from Usuarios where usuario='" + usuario.getText() + "'&& Contraseña='"
                    + contra.getText() + "' && Privilegios='Administrador'");
            while (Ca.next()) {
                r = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(EditarResolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return r;
    }
    private int Fecha2(String f)
    {
        Date date = new Date();
       DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       String fecha3=dateFormat.format(date);
       
       
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
        
        Date fecha1 = null;
        Date fecha2 = null;
        try {

            fecha1 = formatoDelTexto.parse(fecha3);
            fecha2 = formatoDelTexto.parse(f);

        } catch (ParseException ex) {

            ex.printStackTrace();

        }
        return fecha1.compareTo(fecha2);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (vef()) {
            try {
                año = Fecha.getCalendar().get(Calendar.YEAR);
                mes = Fecha.getCalendar().get(Calendar.MONTH) + 1;
                dia = Fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
            } catch (NullPointerException ex) {
                //JOptionPane.showMessageDialog(this, "Al menos selecciona una fecha válida!", "Error!", JOptionPane.INFORMATION_MESSAGE);
            }

            if ((Serie.getText().equals("")) || Inicio.getText().equals("") || Final.getText().equals("") || NR.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Revise que no tenga algun campo vacio", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);

                //JOptionPane.showMessageDialog(null, "Dia "+dia+" Mes "+mes+" Año "+año);
            } else {
                if (Integer.parseInt(Inicio.getText()) >= Integer.parseInt(Final.getText()) || Integer.parseInt(Inicio.getText()) == 0 || Integer.parseInt(Final.getText()) == 0) {
                    JOptionPane.showMessageDialog(this, "Rango Incorrecto");

                } else {
                     String f=año+"-"+mes+"-"+dia;
                    if (año != 0 && dia != 0 && mes != 0) 
                    {   if(Fecha2(f)>=0)
                        {
                            String arre[] = new String[5];
                        arre[0] = Serie.getText();
                        arre[1] = NR.getText();
                        arre[2] = Inicio.getText();
                        arre[3] = Final.getText();
                        arre[4] = id;
                        llenarResolucion2(arre, año, mes, dia);
                        JOptionPane.showMessageDialog(this, "Dato Editado");
                        Res n=new Res();
                        n.setVisible(true);
                        dispose();
                        }
                        else
                    {
                         JOptionPane.showMessageDialog(null, "Fecha incoherente: "+f);
                    }
                        

                    } else {
                        String arre[] = new String[5];
                        arre[0] = Serie.getText();
                        arre[1] = NR.getText();
                        arre[2] = Inicio.getText();
                        arre[3] = Final.getText();
                        arre[4] = id;
                        llenarResolucion(arre);
                        JOptionPane.showMessageDialog(this, "Dato Editado");
                        Res n=new Res();
                        n.setVisible(true);
                        dispose();
                    }

                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Acceso Denegado", "Error", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Res tz = new Res();
        tz.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void contraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraFocusGained
    contra.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_contraFocusGained
    private void llenarResolucion(String ar[]) {
        try {
            PreparedStatement ActualizarProveedor = tr.prepareStatement("UPDATE Resoluciones set Serie='" + ar[0] + "',NoR='" + ar[1] + "' "
                    + ", RangoI='" + ar[2] + "',RangoF='" + ar[3] + "'where id='" + ar[4] + "'");
            ActualizarProveedor.executeUpdate();
            ActualizarProveedor.close();
        } catch (SQLException ex) {
            Logger.getLogger(EditarResolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
        //&& RangoI='"+ar[1]+"'&&NoR='"+ar[5]+"'&& RangoF='"+ar[2]+"'
    }
    private void llenarResolucion2(String ar[], int x, int y, int z) {
        try {
            PreparedStatement ActualizarProveedor = tr.prepareStatement("UPDATE Resoluciones set Serie='" + ar[0] + "',NoR='" + ar[1] + "' "
                    + ", RangoI='" + ar[2] + "',RangoF='" + ar[3] + "', Fecha='"+x+"-"+y+"-"+z+"'where id='" + ar[4] + "'");
            ActualizarProveedor.executeUpdate();
            ActualizarProveedor.close();
        } catch (SQLException ex) {
            Logger.getLogger(EditarResolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
        //&& RangoI='"+ar[1]+"'&&NoR='"+ar[5]+"'&& RangoF='"+ar[2]+"'
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarResolucion(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JTextField Final;
    private javax.swing.JTextField Inicio;
    private javax.swing.JTextField NR;
    private javax.swing.JTextField Serie;
    private javax.swing.JPasswordField contra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
