/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario2;

import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;




/**
 *
 * @author sys515
 */
public class MostrarLotes extends javax.swing.JFrame {
    
    Conexion con = new Conexion();
   private int tp=0;
   private int n2=0;
   private int año=0;
   private int mes=0;
   private int dia=0;
   private String Usuario;
    Connection Consulta = con.conexion();
    String[] ML= new String[4];
     DefaultTableModel modeloBusqueda = new DefaultTableModel() {
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };
    /**
     * Creates new form MostrarLotes
     */
    public MostrarLotes(String Marca,String Nombre,String Uni,String Serie,String Numero) {
        initComponents();
        this.setSize(1300, 1000);
        this.setResizable(false);
   
        this.setTitle("Stock "+Nombre +", "+Marca+" - Sistema Inventario BTZ");
        PanelEditar.setVisible(false);
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE); 
        Nuevo1.setVisible(false); Nuevo2.setVisible(false); Nuevo3.setVisible(false);
        CostoN.setVisible(false);PUN.setVisible(false); PTN.setVisible(false);
        brz.setVisible(false);
        CostoE.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
             CostoE.setText(null);
             tp=0;
             n2=0;
            }
        });
       
          
            
            modeloBusqueda.addColumn("No Lote");
            modeloBusqueda.addColumn("Fecha");
            modeloBusqueda.addColumn("Cantidad");
            modeloBusqueda.addColumn("Costo Unitario");
            modeloBusqueda.addColumn("Costo Total");
            modeloBusqueda.addColumn("Descripcion");
            modeloBusqueda.addColumn("Precio Unitario");
            modeloBusqueda.addColumn("Precio Total");
            modeloBusqueda.addColumn("Proveedor");
            modeloBusqueda.addColumn("Ganancia");
            Lote.setModel(modeloBusqueda);
            
            
           
      
            
       
        Lote.setVisible(true);
        Lote.getColumn("No Lote").setPreferredWidth(15);
        Lote.getColumn("Fecha").setPreferredWidth(120);
        Lote.getColumn("Cantidad").setPreferredWidth(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Editar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lote = new rojerusan.RSTableMetro();
        PanelEditar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CantidadE = new javax.swing.JTextField();
        CostoE = new javax.swing.JTextField();
        DescripcionE = new javax.swing.JTextField();
        GananciaE = new javax.swing.JTextField();
        Fecha = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        Validar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Nuevo1 = new javax.swing.JLabel();
        PUN = new javax.swing.JLabel();
        Nuevo3 = new javax.swing.JLabel();
        Nuevo2 = new javax.swing.JLabel();
        PTN = new javax.swing.JLabel();
        CostoN = new javax.swing.JLabel();
        brz = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Contra = new javax.swing.JPasswordField();
        NO = new javax.swing.JLabel();
        Usuarios = new javax.swing.JComboBox<>();

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Editar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 111, 172));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Lote.setColorBackgoundHead(new java.awt.Color(0, 141, 232));
        Lote.setComponentPopupMenu(jPopupMenu1);
        Lote.setFuenteHead(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Lote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoteFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(Lote);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1260, 430));

        PanelEditar.setBackground(new java.awt.Color(62, 142, 194));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PanelEditarFocusLost(evt);
            }
        });
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });
        PanelEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Costo Unitario");
        PanelEditar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        NL.setBackground(new java.awt.Color(12, 161, 239));
        NL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NL.setForeground(new java.awt.Color(255, 255, 255));
        NL.setText("NO:");
        PanelEditar.add(NL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ganancia");
        PanelEditar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        CantidadE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadEKeyTyped(evt);
            }
        });
        PanelEditar.add(CantidadE, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 69, -1));

        CostoE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CostoEFocusLost(evt);
            }
        });
        CostoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoEActionPerformed(evt);
            }
        });
        CostoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostoEKeyTyped(evt);
            }
        });
        PanelEditar.add(CostoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 87, -1));
        PanelEditar.add(DescripcionE, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 160, -1));

        GananciaE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GananciaEKeyTyped(evt);
            }
        });
        PanelEditar.add(GananciaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 50, -1));

        Fecha.setDateFormatString("yyyy-MM-d");
        PanelEditar.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 138, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descripcion");
        PanelEditar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        Validar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Validar.setForeground(new java.awt.Color(255, 255, 255));
        Validar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-ok-32.png"))); // NOI18N
        Validar.setText("Validar");
        Validar.setContentAreaFilled(false);
        Validar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-de-acuerdo-30.png"))); // NOI18N
        Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarActionPerformed(evt);
            }
        });
        PanelEditar.add(Validar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad");
        PanelEditar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        Nuevo1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nuevo1.setForeground(new java.awt.Color(255, 255, 255));
        Nuevo1.setText("Nuevo Costo Total");
        PanelEditar.add(Nuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        PUN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PUN.setForeground(new java.awt.Color(255, 255, 255));
        PUN.setText("Cantidad");
        PanelEditar.add(PUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        Nuevo3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nuevo3.setForeground(new java.awt.Color(255, 255, 255));
        Nuevo3.setText("Nuevo Precio Total");
        PanelEditar.add(Nuevo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        Nuevo2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nuevo2.setForeground(new java.awt.Color(255, 255, 255));
        Nuevo2.setText("Nuevo Precio Unitario");
        PanelEditar.add(Nuevo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        PTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PTN.setForeground(new java.awt.Color(255, 255, 255));
        PTN.setText("Cantidad");
        PanelEditar.add(PTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        CostoN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CostoN.setForeground(new java.awt.Color(255, 255, 255));
        CostoN.setText("Cantidad");
        PanelEditar.add(CostoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        brz.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        brz.setForeground(new java.awt.Color(255, 255, 255));
        brz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-ok-32.png"))); // NOI18N
        brz.setText("Confirmar");
        brz.setContentAreaFilled(false);
        brz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-de-acuerdo-30.png"))); // NOI18N
        brz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brzActionPerformed(evt);
            }
        });
        PanelEditar.add(brz, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 160, 40));

        jLabel5.setBackground(new java.awt.Color(12, 161, 239));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha");
        PanelEditar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel8.setBackground(new java.awt.Color(12, 161, 239));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modificar");
        PanelEditar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel10.setBackground(new java.awt.Color(12, 161, 239));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lote");
        PanelEditar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel11.setBackground(new java.awt.Color(12, 161, 239));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NO:");
        PanelEditar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-eliminar-50.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-eliminar-filled-50.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelEditar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 50));

        Contra.setText("jPasswordField1");
        PanelEditar.add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 120, -1));

        NO.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NO.setForeground(new java.awt.Color(255, 255, 255));
        NO.setText("Permiso");
        PanelEditar.add(NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, -1, -1));

        jPanel1.add(PanelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 180));

        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 100, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

         private void us() {
        AutoCompleteDecorator.decorate(Usuarios);
        Usuarios.removeAllItems();
        try {
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT NombreC FROM Cliente");
            while (Ca.next()) {

                Usuarios.addItem(Ca.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
       us();
        int seleccionar = 0;
        seleccionar = Lote.getSelectedRow();
        Boolean s=true;
        if (seleccionar == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un fila valida");
        } 
        else
        {
            if(s==true)
            {
                
                PanelEditar.setVisible(true);
                llenarPanel();
                

            }
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarActionPerformed

    private void ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarActionPerformed
        if(CantidadE.getText().equals("")||CostoE.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Campo(s) Vacios(s)");

        }
        else
        {
            String[] datos=new String [4];
            datos[0]=CantidadE.getText(); datos[1]=CostoE.getText();datos[2]=DescripcionE.getText();datos[3]=GananciaE.getText();
            calcular(datos);
            validar(datos);
           
            
        }
    }//GEN-LAST:event_ValidarActionPerformed
    private void validar(String x[])
    {
        BigDecimal otro;
        otro=PrecioUnitario(Double.parseDouble(CostoE.getText()),Double.parseDouble(GananciaE.getText()),Double.parseDouble(CostoE.getText()));
        PUN.setText(String.valueOf(otro));
        PUN.setVisible(true);
        Nuevo2.setVisible(true);
        BigDecimal otro2;
        otro2=PrecioTotal(PrecioUnitario(Double.parseDouble(CostoE.getText()),Double.parseDouble(GananciaE.getText()),Double.parseDouble(CostoE.getText())),Double.parseDouble(CantidadE.getText()));
        PTN.setText(String.valueOf(otro2));
        PTN.setVisible(true);
        Nuevo3.setVisible(true);
    }
    private BigDecimal PrecioUnitario(Double PreU,Double G,Double CU)
    {
        BigDecimal w=BigDecimal.valueOf(PreU).multiply(BigDecimal.valueOf(G)).setScale(2, BigDecimal.ROUND_DOWN);      
        w=w.divide(BigDecimal.valueOf(100)).setScale(2, BigDecimal.ROUND_DOWN);
        w=w.add(BigDecimal.valueOf(CU)).setScale(2, BigDecimal.ROUND_DOWN);
        return w;
    }
    private BigDecimal PrecioTotal(BigDecimal Uni,Double T)
    {
        return Uni.multiply(BigDecimal.valueOf(T)).setScale(2, BigDecimal.ROUND_DOWN);
    }
    private void CantidadEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadEKeyTyped
              int k = (int) evt.getKeyChar();
        if (k >= 97 && k <= 127 || k >= 58 && k <= 97) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 241 || k == 209) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k >= 33 && k <= 47) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar Simbolos!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 10) {
            CantidadE.transferFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadEKeyTyped

    private void CostoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostoEKeyTyped
        int k = (int) evt.getKeyChar();
        if (k == 10) {
            CostoE.transferFocus();
            tp=1;
            CostoE.setText(""+x(Double.parseDouble(CostoE.getText())));

        }
        else{
            if(k==46)
            {
                tp++;
            }

            if(tp>1)
            {
                evt.setKeyChar((char) KeyEvent.VK_CLEAR);
                JOptionPane.showMessageDialog(null, "Punto de mas", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
                tp--;
            }

            if (k >= 97 && k <= 127 || k >= 58 && k <= 97) {
                evt.setKeyChar((char) KeyEvent.VK_CLEAR);
                JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
            }
            if (k == 241 || k == 209) {
                evt.setKeyChar((char) KeyEvent.VK_CLEAR);
                JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
            }
            if (k >= 33 && k <= 45 || k==47 ) {
                evt.setKeyChar((char) KeyEvent.VK_CLEAR);
                JOptionPane.showMessageDialog(null, "No puede ingresar Simbolos!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
            }

        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoEKeyTyped

    private void CostoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoEActionPerformed

    private void CostoEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CostoEFocusLost
        try
        {
            CostoE.setText(""+x(Double.parseDouble(CostoE.getText())));
        }
        catch(NumberFormatException ex) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoEFocusLost
 
     private Boolean vef()
    {
       
        
        
        char claves[]=Contra.getPassword();
        String clavedef=new String(claves);
        int c=0;
        try{
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT Usuario, Contraseña, Privilegios FROM Usuarios");
            while (Ca.next()) 
            {
                c++;
                if(c!=0)
                {
               // System.out.println(Ca.getString(1)+" -- "+Ca.getString(2));
               // System.out.println(us+"***"+clavedef);
               if((Usuario.equals(Ca.getString(1)))&&(clavedef.equals(Ca.getString(2)))&&Ca.getString(3).equals("Administrador"))
                {
                   return true;
                }
                }
                else
                {
                   return false;
                }
                              
            }
            
        }catch(SQLException ex){
            Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        return false;
    }

    private void brzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brzActionPerformed
        
    }//GEN-LAST:event_brzActionPerformed

    
    private void GananciaEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GananciaEKeyTyped
          int k = (int) evt.getKeyChar();
        if (k >= 97 && k <= 127 || k >= 58 && k <= 97) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 241 || k == 209) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k >= 33 && k <= 47) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar Simbolos!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 10) {
            GananciaE.transferFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_GananciaEKeyTyped

    private void PanelEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelEditarFocusLost
        PanelEditar.setVisible(false);
        PanelEditar.setEnabled(false);
    }//GEN-LAST:event_PanelEditarFocusLost

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
    }//GEN-LAST:event_PanelEditarMouseExited

    private void LoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LoteFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Nuevo1.setVisible(false); Nuevo2.setVisible(false); Nuevo3.setVisible(false);
        CostoN.setVisible(false);PUN.setVisible(false); PTN.setVisible(false);
        brz.setVisible(false);
        PanelEditar.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        Usuario= (String) Usuarios.getSelectedItem();

        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariosActionPerformed
     private BigDecimal x(Double r)
    {
        return BigDecimal.valueOf(r).setScale(2, BigDecimal.ROUND_DOWN);
    }    private void calcular(String x[])
    {
        BigDecimal n=new BigDecimal(0);
        n=BigDecimal.valueOf(Double.valueOf(x[0])).multiply(BigDecimal.valueOf(Double.valueOf(x[1])).setScale(2, BigDecimal.ROUND_DOWN)).setScale(2, BigDecimal.ROUND_DOWN);
        CostoN.setText(String.valueOf(n));
        CostoN.setVisible(true);
        Nuevo1.setVisible(true);
        brz.setVisible(true);
        
    }
   
    private void llenarPanel()
    {
        NL.setText(String.valueOf(Lote.getValueAt(Lote.getSelectedRow(), 0)));
        CantidadE.setText(String.valueOf(Lote.getValueAt(Lote.getSelectedRow(), 2)));
        ML[0]=String.valueOf(Lote.getValueAt(Lote.getSelectedRow(), 2));
        CostoE.setText(String.valueOf(Lote.getValueAt(Lote.getSelectedRow(), 3)));
        ML[1]=String.valueOf(Lote.getValueAt(Lote.getSelectedRow(), 3));
        DescripcionE.setText(String.valueOf(Lote.getValueAt(Lote.getSelectedRow(), 5)));
        ML[2]=String.valueOf(Lote.getValueAt(Lote.getSelectedRow(), 5));
        String Ganancia=String.valueOf(Lote.getValueAt(Lote.getSelectedRow(), 9));
        GananciaE.setText(Ganancia.substring(0,Ganancia.length()-1));
        ML[3]=Ganancia;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarLotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarLotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarLotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarLotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new MostrarLotes("","","","","").setVisible(true);
            }
        });
    }
    private int Fecha2(String f)
    {
        Date date = new Date();
       DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       String fecha3=dateFormat.format(date);
       
       
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
        
        Date fecha1 = null;
        Date fecha2 = null;
        try {

            fecha1 = formatoDelTexto.parse(fecha3);
            fecha2 = formatoDelTexto.parse(f);

        } catch (ParseException ex) {

            ex.printStackTrace();

        }
        return fecha1.compareTo(fecha2);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadE;
    private javax.swing.JPasswordField Contra;
    private javax.swing.JTextField CostoE;
    private javax.swing.JLabel CostoN;
    private javax.swing.JTextField DescripcionE;
    private javax.swing.JMenuItem Editar;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JTextField GananciaE;
    private rojerusan.RSTableMetro Lote;
    private javax.swing.JLabel NL;
    private javax.swing.JLabel NO;
    private javax.swing.JLabel Nuevo1;
    private javax.swing.JLabel Nuevo2;
    private javax.swing.JLabel Nuevo3;
    private javax.swing.JLabel PTN;
    private javax.swing.JLabel PUN;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JComboBox<String> Usuarios;
    private javax.swing.JButton Validar;
    private javax.swing.JButton brz;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
