/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chr97lubuntu
 */
public class Res extends javax.swing.JFrame {

    Conexion con = new Conexion();

    Connection Consulta = con.conexion();
    boolean verificado;
    DefaultTableModel modeloBusqueda = new DefaultTableModel() {
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };

    //
    //Icon icono = new ImageIcon(getClass().getResource("ruta local"));
    /**
     * Creates new form log
     */
    public Res() {
        initComponents();
        this.setTitle("Resoluciones");
        this.setResizable(false);
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        modeloBusqueda.addColumn("Serie");
        modeloBusqueda.addColumn("Rango Incial");
        modeloBusqueda.addColumn("Rango Final");
        modeloBusqueda.addColumn("Rango Actual");
        modeloBusqueda.addColumn("Fecha");
        modeloBusqueda.addColumn("Número de Resolución ");
        modeloBusqueda.addColumn("Estado");
        Res.setModel(modeloBusqueda);
        Res.getColumn("Serie").setPreferredWidth(50);
        String datos[] = new String[7];
        try {

            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("select Serie,RangoI,NoR,Fecha,RangoF,INCREMENTO,Activo from Resoluciones");
            while (Ca.next()) {
                datos[0] = Ca.getString(1);
                datos[1] = Ca.getString(2);
                datos[2] = Ca.getString(5);
                datos[3] = Ca.getString(6);
                datos[4] = Ca.getString(4);
                datos[5] = Ca.getString(3);
                if(Ca.getString(7).equals("1"))
                {
                    datos[6] = "Activo";
                }
                else
                {
                    datos[6] = "Inactivo";
                }
                modeloBusqueda.addRow(datos);

            }
            Res.setModel(modeloBusqueda);
        } catch (SQLException ex) {
            Logger.getLogger(Res.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void actualiz() {
        modeloBusqueda.setRowCount(0);
        String datos[] = new String[7];
        try {

            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("select Serie,RangoI,NoR,Fecha,RangoF,INCREMENTO,Activo from Resoluciones");
            while (Ca.next()) {
                datos[0] = Ca.getString(1);
                datos[1] = Ca.getString(2);
                datos[2] = Ca.getString(5);
                datos[3] = Ca.getString(6);
                datos[4] = Ca.getString(4);
                datos[5] = Ca.getString(3);
                if(Ca.getString(7).equals("1"))
                {
                    datos[6] = "Activo";
                }
                else
                {
                    datos[6] = "Inactivo";
                }
                modeloBusqueda.addRow(datos);

            }
            Res.setModel(modeloBusqueda);
        } catch (SQLException ex) {
            Logger.getLogger(Res.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Res = new javax.swing.JTable();

        jMenuItem1.setText("Activar Resolución");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Editar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 111, 172));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resoluciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, 44));

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-pie-de-página-del-documento-100.png"))); // NOI18N
        jButton5.setText("Ingresar Resolución");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-pie-de-página-del-documento-filled-100.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 119));

        Res.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Res.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(Res);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 920, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Resolucion nr = new Resolucion();
        nr.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        SubVentas bez = new SubVentas();
        bez.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
    private void Poner_falos() {
        try {
            PreparedStatement ActualizarProveedor = Consulta.prepareStatement("UPDATE Resoluciones SET Activo=0");
            ActualizarProveedor.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Res.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void AcitvarRes(int id) {
        try {
            PreparedStatement ActualizarProveedor = Consulta.prepareStatement("UPDATE Resoluciones SET Activo=1 where id='" + id + "'");
            ActualizarProveedor.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Res.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int seleccionar = 0;
        seleccionar = Res.getSelectedRow();

        if (seleccionar == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un fila valida");

        } else {
            String[] valores = new String[7];
            for (int i = 0; i < 7; i++) {
                valores[i] = String.valueOf(Res.getValueAt(Res.getSelectedRow(), i));
            }
            int id = obtener_id(valores);
            Poner_falos();
            AcitvarRes(id);
            actualiz();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int seleccionar = 0;
        seleccionar = Res.getSelectedRow();

        if (seleccionar == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un fila valida");

        } else {
            String[] valores = new String[8];
            for (int i = 0; i < 7; i++) {
                valores[i] = String.valueOf(Res.getValueAt(Res.getSelectedRow(), i));
            }
            int id = obtener_id(valores);
            valores[7]=String.valueOf(id);
            EditarResolucion editar=new EditarResolucion(valores);
            editar.setVisible(true);
            dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    private int obtener_id(String x[]) {

        int id = 0;

        try {
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT id FROM Resoluciones where Serie='" + x[0] + "'&&RangoI='" + x[1] + "'&& NoR='" + x[5] + "'&&"
                    + "INCREMENTO='" + x[3] + "'&&RangoF='" + x[2] + "'&&Activo='" + x[6] + "' ");
            while (Ca.next()) {
                id = Integer.parseInt(Ca.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Res.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Res.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Res().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Res;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
