/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario2;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author chr97lubuntu
 */
public class verprove extends javax.swing.JFrame {
      Conexion con = new Conexion();
   
    Connection Consulta = con.conexion();
        Connection cn = con.conexion();

        private String Usuario=null;
        private String[] DI=new String [6];

    /**
     * Creates new form verprove
     */
    public verprove() {
        initComponents();
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE); 
        DefaultTableModel modelo=new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        PanelEditar.setVisible(false);
        this.setTitle("Proveedores - Sistema Inventario BTZ");
        modelo.addColumn("Nit");
        modelo.addColumn("Empresa");
        modelo.addColumn("Representante");
        modelo.addColumn("Telefono");
        modelo.addColumn("Correo");
        modelo.addColumn("Direccion");
        tpro.setModel(modelo);
        String datos[] = new String[6];
        try {
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT Nit, NombreV, Representante, Numero,Correo,Direccion FROM Proveedor;");
            while(Ca.next()){
                datos[0] = Ca.getString(1);
                datos[1] = Ca.getString(2);
                datos[2] = Ca.getString(3);
                datos[3] = Ca.getString(4);
                datos[4] = Ca.getString(5);
                datos[5] = Ca.getString(6);
                modelo.addRow(datos);
                
                
            }
            tpro.setModel(modelo);
            
        }catch(SQLException ex){
            Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }
        tpro.setVisible(true);
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPopuMenu1 = new rojerusan.RSPopuMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpro = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Edit5 = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        NO = new javax.swing.JLabel();
        Dir = new javax.swing.JLabel();
        Nit = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Edit3 = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        Edit4 = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Contra = new javax.swing.JPasswordField();
        Usuarios = new javax.swing.JComboBox<>();
        NO1 = new javax.swing.JLabel();
        Edit6 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Dir1 = new javax.swing.JLabel();
        Edit7 = new javax.swing.JLabel();

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        rSPopuMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(189, 189, 189));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nit", "Nombre", "Representante", "Direccion", "Telefono"
            }
        ));
        tpro.setComponentPopupMenu(rSPopuMenu1);
        jScrollPane1.setViewportView(tpro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 622, 478));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientead15.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 37, 38));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizara17.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 39, 38));

        Edit5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Edit5.setForeground(new java.awt.Color(255, 255, 255));
        Edit5.setText("Modificar");
        jPanel1.add(Edit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        PanelEditar.setBackground(new java.awt.Color(62, 142, 194));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelEditar.setLayout(null);

        NO.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NO.setForeground(new java.awt.Color(255, 255, 255));
        NO.setText("Permiso");
        PanelEditar.add(NO);
        NO.setBounds(20, 280, 95, 17);

        Dir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Dir.setForeground(new java.awt.Color(255, 255, 255));
        Dir.setText("Dirección");
        PanelEditar.add(Dir);
        Dir.setBounds(10, 200, 80, 30);
        PanelEditar.add(Nit);
        Nit.setBounds(110, 100, 80, 30);

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        PanelEditar.add(Nombre);
        Nombre.setBounds(10, 30, 80, 30);

        Edit3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Edit3.setForeground(new java.awt.Color(255, 255, 255));
        Edit3.setText("Nombre");
        PanelEditar.add(Edit3);
        Edit3.setBounds(10, 10, 95, 17);

        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        PanelEditar.add(Apellido);
        Apellido.setBounds(110, 30, 120, 30);

        Modificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-editar-propiedad-32.png"))); // NOI18N
        Modificar.setText("Modificar");
        Modificar.setContentAreaFilled(false);
        Modificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-editar-propiedad-30.png"))); // NOI18N
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        PanelEditar.add(Modificar);
        Modificar.setBounds(30, 400, 150, 42);

        Edit4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Edit4.setForeground(new java.awt.Color(255, 255, 255));
        Edit4.setText("Representante");
        PanelEditar.add(Edit4);
        Edit4.setBounds(110, 10, 120, 17);

        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });
        PanelEditar.add(Direccion);
        Direccion.setBounds(10, 230, 200, 30);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-eliminar-50.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-eliminar-filled-50.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelEditar.add(jButton3);
        jButton3.setBounds(40, 450, 160, 30);

        Contra.setText("jPasswordField1");
        PanelEditar.add(Contra);
        Contra.setBounds(30, 360, 112, 32);

        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        PanelEditar.add(Usuarios);
        Usuarios.setBounds(30, 310, 130, 32);

        NO1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NO1.setForeground(new java.awt.Color(255, 255, 255));
        NO1.setText("Telefono");
        PanelEditar.add(NO1);
        NO1.setBounds(10, 80, 95, 17);

        Edit6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Edit6.setForeground(new java.awt.Color(255, 255, 255));
        Edit6.setText("Nit");
        PanelEditar.add(Edit6);
        Edit6.setBounds(110, 80, 21, 17);

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });
        PanelEditar.add(Telefono);
        Telefono.setBounds(10, 100, 82, 30);

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CorreoKeyTyped(evt);
            }
        });
        PanelEditar.add(Correo);
        Correo.setBounds(10, 170, 200, 30);

        Dir1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Dir1.setForeground(new java.awt.Color(255, 255, 255));
        Dir1.setText("Correo");
        PanelEditar.add(Dir1);
        Dir1.setBounds(10, 140, 80, 30);

        jPanel1.add(PanelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 290, 500));

        Edit7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Edit7.setForeground(new java.awt.Color(255, 255, 255));
        Edit7.setText("Proveedores");
        jPanel1.add(Edit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         IngresarProve x=new IngresarProve();
        x.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActionPerformed
     private Boolean vef()
    {
       
        
        
        char claves[]=Contra.getPassword();
        String clavedef=new String(claves);
        int c=0;
        try{
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT Usuario, Contraseña, Privilegios FROM Usuarios");
            while (Ca.next()) 
            {
                c++;
                if(c!=0)
                {
               // System.out.println(Ca.getString(1)+" -- "+Ca.getString(2));
               // System.out.println(us+"***"+clavedef);
               if((Usuario.equals(Ca.getString(1)))&&(clavedef.equals(Ca.getString(2)))&&Ca.getString(3).equals("Administrador"))
                {
                   return true;
                }
                }
                else
                {
                   return false;
                }
                              
            }
            
        }catch(SQLException ex){
            Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        return false;
    }
       private Boolean ValidarNit(String nit,String onit)
     {
        if(nit.equals(onit))
        {
            return true;
        }
        else
        {
            try 
            {
                Statement sx = Consulta.createStatement();
                ResultSet Ca = sx.executeQuery("Select id from Proveedor where Nit='"+nit+"'");
                while(Ca.next())
                {
                    return false;
                }
                return true;
            } catch (SQLException ex) {
                Logger.getLogger(verclientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        return false;
        }
     }
       private void actua() {
        try {

            DefaultTableModel modeloBusqueda = new DefaultTableModel() {
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };
             modeloBusqueda.addColumn("Nit");
        modeloBusqueda.addColumn("Empresa");
        modeloBusqueda.addColumn("Representante");
        modeloBusqueda.addColumn("Telefono");
        modeloBusqueda.addColumn("Correo");
        modeloBusqueda.addColumn("Direccion");
           
            tpro.setModel(modeloBusqueda);

            String datos[] = new String[6];
            int contar = 0;
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT Nit, NombreV, Representante, Numero, Correo,Direccion FROM Proveedor;");
            while(Ca.next()){
                datos[0] = Ca.getString(1);
                datos[1] = Ca.getString(2);
                datos[2] = Ca.getString(3);
                datos[3] = Ca.getString(4);
                datos[4] = Ca.getString(5);
                datos[5] = Ca.getString(6);
                modeloBusqueda.addRow(datos);
                contar++;
                
            }
            tpro.setModel(modeloBusqueda);
            if (contar == 0) {
                JOptionPane.showMessageDialog(null, "No hay Productos en la base de datos");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
       private String CI(String nit)
     {
        String h="";
        try {
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("Select id from Proveedor where Nit='"+nit+"'");
            while(Ca.next())
            {
               h=Ca.getString(1);
            }
           return h;
        } catch (SQLException ex) {
            Logger.getLogger(verclientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        return h;
     }
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        if(vef()==true)
        {
            String[] datos = new String[6];
            datos[0]=Nit.getText();
            datos[1] = Nombre.getText();
            datos[2] = Apellido.getText();
            datos[3] = Telefono.getText();
            datos[4] = Correo.getText();
            datos[5] = Direccion.getText();
            if(ValidarNit(datos[0],DI[0])==true)
            {
                try {
                    PreparedStatement ActualizarProveedor = cn.prepareStatement("UPDATE Proveedor SET Nit='"+datos[0]+"',NombreV='"+datos[1]+"',Representante='"+datos[2]+"',Numero='"+datos[3]+"',Direccion='"+datos[5]+"',Correo='"+datos[4]+"' where id= '"+CI(DI[0])+"'");
                    ActualizarProveedor.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
                }

                actua();
                PanelEditar.setVisible(false);
                Edit5.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Se modifico con exito el registro");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Este nit ya esta registrado");

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Acceso Denegado");
        }
        PanelEditar.setVisible(false);
        Contra.setText("*****");
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PanelEditar.setVisible(false);
        Edit5.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        Usuario= (String) Usuarios.getSelectedItem();

        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariosActionPerformed
     private void us() {
        AutoCompleteDecorator.decorate(Usuarios);
        Usuarios.removeAllItems();
        try {
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT Usuario FROM Usuarios where  Privilegios='Administrador'");
            while (Ca.next()) {

                Usuarios.addItem(Ca.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        int k = (int) evt.getKeyChar();
        if (k >= 97 && k <= 127 || k >= 58 && k <= 97) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 241 || k == 209) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k >= 33 && k <= 47) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar Simbolos!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 10) {
            Telefono.transferFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoKeyTyped

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 actua();

    }//GEN-LAST:event_jButton2ActionPerformed
     private void llenarCamposAc()
    {
        Nit.setText(String.valueOf(tpro.getValueAt(tpro.getSelectedRow(), 0)));
        Nombre.setText(String.valueOf(tpro.getValueAt(tpro.getSelectedRow(), 1)));
        Apellido.setText(String.valueOf(tpro.getValueAt(tpro.getSelectedRow(), 2)));
        Telefono.setText(String.valueOf(tpro.getValueAt(tpro.getSelectedRow(), 3)));
        Direccion.setText(String.valueOf(tpro.getValueAt(tpro.getSelectedRow(), 5)));
        Correo.setText(String.valueOf(tpro.getValueAt(tpro.getSelectedRow(), 4)));
       
    }
  
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            us();
        int seleccionar = 0;
        seleccionar = tpro.getSelectedRow();
        Boolean xp=true;
        if (seleccionar == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un fila valida");
        } else {
            if (xp == true) {
                PanelEditar.setVisible(true);
                Edit5.setEnabled(true);
                llenarCamposAc();
               
                 
                 DI[0]=Nit.getText();
                 DI[1]=Nombre.getText();
                 DI[2]=Apellido.getText();
                 DI[3]=Telefono.getText();
                 DI[4]=Correo.getText();
                 DI[5]=Direccion.getText();
                //actualizar(seleccionar);
                //actua();
            } else {
                JOptionPane.showMessageDialog(null, "Acceso Denegado");

            }
        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Menu x=new Menu();
        x.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verprove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JPasswordField Contra;
    private javax.swing.JTextField Correo;
    private javax.swing.JLabel Dir;
    private javax.swing.JLabel Dir1;
    private javax.swing.JTextField Direccion;
    private javax.swing.JLabel Edit3;
    private javax.swing.JLabel Edit4;
    private javax.swing.JLabel Edit5;
    private javax.swing.JLabel Edit6;
    private javax.swing.JLabel Edit7;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel NO;
    private javax.swing.JLabel NO1;
    private javax.swing.JTextField Nit;
    private javax.swing.JTextField Nombre;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JTextField Telefono;
    private javax.swing.JComboBox<String> Usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSPopuMenu rSPopuMenu1;
    private javax.swing.JTable tpro;
    // End of variables declaration//GEN-END:variables
}
